/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#1b1b1e",
        "error": "#ba1a1a",
        "secondary-fixed": "#e3e1ec",
        "on-primary-fixed-variant": "#005236",
        "on-error": "#ffffff",
        "surface-tint": "#006c49",
        "on-background": "#1b1b1e",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#2c3a4c",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#0d1c2d",
        "primary": "#006c49",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#4edea3",
        "on-tertiary": "#ffffff",
        "surface-dim": "#dcd9dd",
        "on-primary-container": "#00422b",
        "on-tertiary-fixed-variant": "#39485a",
        "tertiary-fixed-dim": "#b9c8de",
        "tertiary": "#516072",
        "on-secondary-fixed-variant": "#46464e",
        "surface-variant": "#e4e1e6",
        "pure-surface": "#FFFFFF",
        "whisper-border": "rgba(226,232,240,0.5)",
        "background": "#fbf8fc",
        "outline-variant": "#bbcabf",
        "secondary-fixed-dim": "#c6c5cf",
        "on-secondary-container": "#63646c",
        "error-rose": "#E11D48",
        "on-secondary-fixed": "#1a1b22",
        "surface-container-high": "#eae7eb",
        "secondary-container": "#e3e1ec",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f6f2f7",
        "tertiary-container": "#95a4b9",
        "primary-container": "#10b981",
        "surface-container-highest": "#e4e1e6",
        "primary-fixed": "#6ffbbe",
        "inverse-primary": "#4edea3",
        "tertiary-fixed": "#d4e4fa",
        "outline": "#6c7a71",
        "on-primary-fixed": "#002113",
        "on-surface-variant": "#3c4a42",
        "surface-bright": "#fbf8fc",
        "secondary": "#5d5e66",
        "surface": "#fbf8fc",
        "surface-container-lowest": "#ffffff",
        "canvas-white": "#F9FAFB",
        "inverse-surface": "#303033",
        "surface-container": "#f0edf1",
        "inverse-on-surface": "#f3f0f4"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "4rem",
        "margin-mobile": "1rem",
        "container-max": "1400px",
        "margin-tablet": "2rem",
        "gutter": "2rem",
        "section-gap-mobile": "clamp(3rem, 8vw, 6rem)",
        "section-gap-desktop": "clamp(6rem, 10vw, 12rem)"
      },
      fontFamily: {
        "body-lg": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "display-xl": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "mono-data": ["Geist Mono", "monospace"],
        "headline-md": ["Geist", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["1.125rem", { "lineHeight": "1.65", "fontWeight": "400" }],
        "label-sm": ["0.8125rem", { "lineHeight": "1.2", "fontWeight": "500" }],
        "body-md": ["1rem", { "lineHeight": "1.65", "fontWeight": "400" }],
        "display-xl": ["clamp(2.25rem, 5vw, 3.75rem)", { "lineHeight": "1.1", "letterSpacing": "-0.025em", "fontWeight": "800" }],
        "headline-lg": ["2.5rem", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "mono-data": ["0.8125rem", { "lineHeight": "1", "fontWeight": "400" }],
        "headline-md": ["1.75rem", { "lineHeight": "1.25", "fontWeight": "700" }]
      }
    }
  },
  plugins: [],
}